### ISSUE TITLE
Add Responsiveness. Mobile View not supported as of now.

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#10]
# Current Behavior:
![screenshot](https://user-images.githubusercontent.com/13948542/45904188-eaea3200-be09-11e8-8daa-500747ff7e7f.png)

**Comment by jaykay12** [comment]
# Required Mobile-View layout

![80e2221a-31e7-477c-86fe-b54bdebdc5f8](https://user-images.githubusercontent.com/13948542/45918286-4b2cb280-bea2-11e8-913f-cd0fc3ec5a35.jpeg)

**Comment by Harshish** [comment]
WIP

**Comment by jaykay12** [comment]
@Harshish Kindly stick to the UI, I posted above.

**Comment by Harshish** [comment]
Replicating the above layout will change the desktop layout too. Like Team 1 and Team 2 are in different rows now but for above layout they need to be in same row. Please comment whether I should continue.

**Comment by jaykay12** [comment]
@Harshish Kindly confirm if the below layout is possible for mobile-view or not?
**Keeping the web-view intact.**

![check](https://user-images.githubusercontent.com/13948542/46308088-5e442e80-c5d6-11e8-83f5-9c2f3feb1ee5.jpeg)

**Comment by Harshish** [comment]
@jaykay12 Keeping the web view intact while making this mobile view is the main problem which I am facing. Let me see if I can figure out some alternative to make it possible, it may take some time.

**Comment by savitoj98** [comment]
Is anybody working on this. Can i also try it?

**Comment by jaykay12** [comment]
Yeah Sure @savitoj98 you can also give it a try. Infact, @Harshish is also trying to resolve the same issue.

**Comment by jaykay12** [comment]
Resolved by @savitoj98 with PR #20
