### ISSUE TITLE
Remove Background Color in Dropdowns

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#15]
**Current Behavior:** 
![screenshot from 2018-09-25 12-24-11](https://user-images.githubusercontent.com/13948542/45997757-4c3a2b80-c0be-11e8-827a-88a3ce7720c6.png)

**Required Behavior:**
The current background color, blue needs to be replaced with white so, that further #14 can be resolved.
Change needs to be done, for all the dropdowns

**Some Intuition:**
I tried this but in vain:
`../static/styles/styles.css`

> .btn-outline-primary:hover {
>        background-color: white;
> }
>

**Comment by Harshish** [comment]
Please assign this to me I'll work on it

**Comment by jaykay12** [comment]
@Harshish I would love to assign it to you, but the issue has been resolved by @Adi2612  #16 
You can still try resolving other current issues as well.
