### ISSUE TITLE
Redesign the Results

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#17]
**Current Behavior**: Minimalist Design just showing the Winner with the Flag

**Required Behavior**: Good Design, showing the name & the flag of the winner nation.

Add all the assets: Images, GIFs etc at `Web-App/static/assets/`

**Comment by BrandonDH** [comment]
Hey @jaykay12 this is the current behavior correct? I just want to make sure before I dive in. Thanks!
![screen shot 2018-10-01 at 2 10 52 pm](https://user-images.githubusercontent.com/5695373/46307050-dfbea100-c583-11e8-91fc-10dc3cea701c.png)

**Comment by jaykay12** [comment]
Yes @BrandonDH This is the current layout. It's just a minimal design as of now.

**Comment by adi44** [comment]
I would like to work

**Comment by jaykay12** [comment]
@adi44 Surely you can work upon this issue. I don't think @BrandonDH has started off with resolving this issue.

**Comment by savitoj98** [comment]
Can i work on this?

**Comment by jaykay12** [comment]
Resolved by @savitoj98 with PR #21
