### ISSUE TITLE
Web-App Needs Redesigning, Using Bootstrap Framework

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#2]

**Comment by samdoj** [comment]
I can help with that.

**Comment by jaykay12** [comment]
Yeahh Sure @samdoj . It will be really helpful.

### Here's the design I have in my mind

![6476042881816657378](https://user-images.githubusercontent.com/13948542/45266848-787b6880-b47f-11e8-8760-d97f89925d63.jpg)

In case, you wish to enhance anything, you are free to do so. :smile:
Do ask me, if you are on it & require some extra specifications.

**Comment by samdoj** [comment]
Hi, how attached to Bootstrap are you?  I think it would be great for the carousel and the dropdown run button, which I assume contains the models.  I feel like the rest of the layout would be way easier and be more responsive if done with flexbox or grid.  Flexbox is universally supported and grid is mostly supported..

**Comment by jaykay12** [comment]
Yes Sure @samdoj Go Ahead. I am not much into UI/UX Design, so haven't used flexbox till yet, but it looks really cool.
Plus, I was thinking of dropdown menu of team selection to be somthing like this:

![7414379951276492277](https://user-images.githubusercontent.com/13948542/45569040-01c5dd00-b87c-11e8-9746-efe2d3ba42d7.jpeg)

Do let me know, if you need some extra assets? All the flags images, I will add in the repo.
