### ISSUE TITLE
Add flaticon to the title

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#5]
flaticon present at `../static/assets/cricket.png` needs to be added as icon in the title.

Current Title: **CricAI: Smart Outcome Prediction System**
Required Title: :cricket: **CricAI: Smart Outcome Prediction System**

**Comment by msaoudallah** [comment]
hey jaykay, please assign this task to me

**Comment by jaykay12** [comment]
@msaoudallah Assigned to you.

**Kindly have a look at the attached image to get more insight of the issue**

![issue](https://user-images.githubusercontent.com/13948542/45917996-97c1bf00-be9d-11e8-9efb-369655dac59f.png)

**Comment by jaykay12** [comment]
I cant add you as the assignee, as you haven't collaborated to the project till now. Only contributors are allowed to be added as assignee.
Facing the same issue: https://github.com/kubernetes/contrib/issues/1161#issuecomment-323574511

**But you can freely work upon this issue & make a PR by making the desired changes.**
