### ISSUE TITLE
Team1 & Team2 Dropdowns must have distinct selection

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/CricAI#9]
Normal cricket match can never have same team playing on both sides, similarly the system requires such provisioning.

**Current Behavior:** Team 1 & Team 2 are having same Dropdown options-list
**Required Behavior:** If Team 1 Dropdown selects `Team A` them Team 2 Dropdown should have `U-Team A` as the option-list, where U signifies all the teams.

If implemented, No team can be selected on both sides, as Team 1 and Team 2 simultaneously.

**Prerequistes:** #8 
Quite easy if it is resolved first.

**Comment by Harshish** [comment]
WIP

**Comment by Harshish** [comment]
I was thinking of loading through python flask itself it would be much easier to implement

**Comment by jaykay12** [comment]
@Harshish Cool, this one is assigned to you.
No, Server-side check is not required. I was thinking of some JavaScript function for this, but couldn't sort it out.

**Comment by Harshish** [comment]
@jaykay12 Alright I'll do it using JS no problem.
